# Generated by Django 5.0.4 on 2024-06-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_date_time',
            field=models.DateTimeField(),
        ),
    ]
