# Generated by Django 5.0.4 on 2024-05-07 18:00

import django.contrib.auth.password_validation
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be alphanumeric', regex='^[a-zA-Z0-9]*$')])),
                ('password', models.CharField(max_length=50, validators=[django.contrib.auth.password_validation.validate_password])),
                ('confirm_password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must contain only digits', regex='^[0-9]*$')])),
                ('Created_account', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
