# Generated by Django 5.0.4 on 2024-05-07 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Created_account',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
