# Generated by Django 5.0.4 on 2024-05-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_person_email_alter_person_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='account_type',
            field=models.CharField(choices=[('User', 'User'), ('Doctor', 'Doctor')], max_length=50, null=True),
        ),
    ]
