# Generated by Django 5.0.4 on 2024-05-08 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_person_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='Created_account',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
