# Generated by Django 5.0.4 on 2024-05-08 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_person_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Created_account',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
