# Generated by Django 5.0.4 on 2024-05-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_person_created_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
