# Generated by Django 5.0.4 on 2024-05-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_person_email_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
