# Generated by Django 5.0.4 on 2024-05-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_person_email_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='account_type',
            field=models.CharField(choices=[('User', 'User'), ('Doctor', 'Doctor')], default='User', max_length=50),
        ),
    ]
