# Generated by Django 5.0.4 on 2024-05-08 18:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_person_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Created_account',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
