# Generated by Django 5.0.4 on 2024-05-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_person_created_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
    ]
