# Generated by Django 5.0.4 on 2024-05-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_person_confirm_password_alter_person_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='created_by',
        ),
    ]
