# Generated by Django 5.0.4 on 2024-05-09 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_person_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='account_type',
            field=models.CharField(choices=[('User', 'User'), ('Doctor', 'Doctor')], default='User', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='confirm_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must contain only digits', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
