# Generated by Django 5.0.4 on 2024-06-18 22:52

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_alter_loginperson_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginperson",
            name="password",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="loginperson",
            name="username",
            field=models.CharField(max_length=50),
        ),
    ]
