# Generated by Django 5.0.4 on 2024-05-09 19:31

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('confirm_password', models.CharField(max_length=100, null=True)),
                ('account_type', models.CharField(choices=[('User', 'User'), ('Doctor', 'Doctor')], default='User', max_length=100)),
                ('phone', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must contain only digits', regex='^[0-9]*$')])),
                ('Created_account', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
