# Generated by Django 5.0.4 on 2024-05-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
