# Generated by Django 5.0.4 on 2024-06-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_person_is_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_logged_in',
        ),
    ]
